apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
  - name: postgres
    image: postgres:latest
    ports:
    - containerPort: 5432
    env:
      - name: POSTGRES_USER
        value: fadjri
      - name: POSTGRES_PASSWORD
        value: fadjri
      - name: POSTGRES_DB
        value: postgres
